### ISSUE TITLE
5.1. Implement metadata required to describe the horizontal partitioning of global tables over the CDBSes

### ISSUE THREAD

**Issue by aprobinda** [aprobinda/proj_ddb_suse17#4]
It is obvious that the statement for the horizontally partitioned (35,70) table:
INSERT INTO PASSAGIER VALUES (84, 'test of db catalogue', 'test', 'D'); 
must go to the 3rd DB only. 
However, a program sends JDBC insert to the 1st database and catches "violated a check constraint" exception, then continues with the 2nd DB available (same exception) until it finally inserts into the correct DB.
See section "5	A Federative DB catalogue"

**Comment by MrImamBux** [comment]
Not applicable due to time constraint and the complexity in implementation.
