### ISSUE TITLE
"5 DB catalogue" not implemented, so 2.2.6.4 is violated: non-partitioned table is CREATEd in every DB instead of in pinatubo ONLY

### ISSUE THREAD

**Issue by aprobinda** [aprobinda/proj_ddb_suse17#6]
test scripts: CREPARTABS.SQL, 02_INSERTAIRPORTS.SQL
Table FLUGHAFEN has no partition.
2.2.6.4.	If no partitioning clause is given, the entire table hast to be stored on the “first” of your CDBSes.
Total: 84 records, all must be stored ONLY in pinatubo. However, SELECT COUNT(*) FROM FLUGHAFEN; also returns 84 for mtshelens and krakatau.

**Comment by MrImamBux** [comment]
If there is no horizontal partitioning of table, that table should be created on all DBs to provide it's availability as "foreign key" to other tables on all DBs.
