### ISSUE TITLE
Encountered ParseException "03_INSERTAIRLINES.sql"

### ISSUE THREAD

**Issue by amitkovski** [aprobinda/proj_ddb_suse17#7]
ParseException; parser.ParseException: Encountered " <LETTER> "U "" at line 1, column 1.
Was expecting one of:
    "CREATE " ...
    "DROP " ...
    "DELETE " ...
    "INSERT " ...
    "SELECT " ...

ParseException starts at <11:24:43.227> in log.
[fedprot.txt](https://github.com/aprobinda/proj_ddb_suse17/files/1269808/fedprot.txt)

**Comment by MrImamBux** [comment]
Fixed, update project and now check to verify @amitkovski

**Comment by amitkovski** [comment]
Confirmed, it works now.
